[workspace]
members = [
    "crates/bankai_hints",
    "crates/stone_verifier_hints",
    "crates/cairo_runner",
    "crates/stwo_prover",
]
exclude = ["tests"]
resolver = "2"

[workspace.dependencies]
cairo-vm-base = { git = "https://github.com/bankaixyz/cairo-vm-base" }
#cairo-vm-base = { path = "../cairo-vm-base" }
mmr-header-accumulator-hints = { git = "https://github.com/bankaixyz/mmr-header-accumulator" }
beacon_types = { git = "https://github.com/bankaixyz/lighthouse.git", package = "types", rev = "9759655"}

alloy-primitives = { version = "0.8.13" }
bls12_381 = {version = "0.8.0"}
serde = { version = "1.0.215", features = ["derive"] }
serde_json = { version = "1.0.133" }
num-bigint = { version = "0.4.1" }
num-traits = { version = "0.2.19" }
bincode = { version = "2.0.1" }
hex = { version = "0.4.3" }
thiserror = { version = "2.0.9" }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20" }
tree_hash = { version = "0.9" }
clap = { version = "4.5.22", features = ["derive"] }
warp = { version = "0.4", features = ["server"] }
tokio = { version = "1.47.1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }

stwo_cairo_prover = { git = "https://github.com/starkware-libs/stwo-cairo" }
stwo_cairo_utils = { git = "https://github.com/starkware-libs/stwo-cairo" }
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo" }
stwo-cairo-serialize = { git = "https://github.com/starkware-libs/stwo-cairo" }
cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo" }
stwo = { git = "https://github.com/starkware-libs/stwo", rev = "d9176e6e22319370a8501f799829b920c0db2eac", features = [
    "parallel",
    "prover",
], default-features = false }
sonic-rs = { version = "0.3.17" }
starknet-ff = { version = "0.3.7" }
