[package]
name = "cairo-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
garaga-zero = { path = "../../cairo/packages/garaga-zero" }
bankai-hints = { path = "../bankai_hints" }
stone-verifier-hints = { path = "../stone_verifier_hints" }
cairo-vm-base.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
num-bigint.workspace = true
hex.workspace = true
beacon_types.workspace = true
tracing.workspace = true
bincode.workspace = true
clap.workspace = true
alloy-primitives = "0.8.13"
bls12_381 = "0.8.0"
tree_hash = "0.8"
tree_hash_derive = "0.8"